### ISSUE TITLE
Docs / web layout issue for "Your first project" in Firefox

### ISSUE THREAD

**Issue by jcbeck37** [typescene/typescene#7]
Steps to Reproduce
1. Open the latest Firefox browser (67.0.4 at time of report)
2. Visit https://typescene.dev/docs/guides/first
3. Maximized window. Zoom is 100% original. Resolution is 1920x1080. (OS = Windows; scaling is 150%).

Expected Result
1. Rendered layout should look the same as what you see in Chrome

Actual Result
1. Rendered layout has float/overlap issues.

**Comment by MicahZoltu** [comment]
Why was this closed?  I am experiencing the exact problem.

**Comment by jcormont** [comment]
The issue was moved to the website repo. Now closed, it should be fixed. Thanks!
