### ISSUE TITLE
Create a project template starter 

### ISSUE THREAD

**Issue by jeanlucaslima** [typescene/typescene#9]
Desired features for this starter:

- initial setup on npm
- git init (just good practice)
- prompt if the user would like to have typescript installed too

**Comment by jeanlucaslima** [comment]
Add `.gitignore`

**Comment by jcormont** [comment]
I've looked at 'git init' before, which can use a custom package to set up a new project. Much like create-react-app does. I don't really have the CLI skills at the moment though. Parking this for later unless someone wants to help.

**Comment by jcormont** [comment]
Done! See https://github.com/typescene/create-typescene-webapp
I will do some more testing before I adjust instructions everywhere else.
